// <auto-generated />
using System;
using BookEFApp.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookEFApp.Dal.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250416122347_dataSeeding")]
    partial class dataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookEFApp.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auteurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateOnly(1980, 12, 31),
                            Nom = "Jean-Claude"
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateOnly(1990, 12, 31),
                            Nom = "Jean-Claude"
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateOnly(2000, 12, 31),
                            Nom = "Jean-Claude"
                        });
                });

            modelBuilder.Entity("BookEFApp.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.ToTable("Livres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuteurId = 1,
                            Date = new DateOnly(2020, 12, 31),
                            Titre = "Le livre 1"
                        },
                        new
                        {
                            Id = 2,
                            AuteurId = 2,
                            Date = new DateOnly(2021, 12, 31),
                            Titre = "Le livre 2"
                        },
                        new
                        {
                            Id = 3,
                            AuteurId = 3,
                            Date = new DateOnly(2022, 12, 31),
                            Titre = "Le livre 3"
                        },
                        new
                        {
                            Id = 4,
                            AuteurId = 3,
                            Date = new DateOnly(2023, 12, 31),
                            Titre = "Le livre 4"
                        });
                });

            modelBuilder.Entity("BookEFApp.Models.Livre", b =>
                {
                    b.HasOne("BookEFApp.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("BookEFApp.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });
#pragma warning restore 612, 618
        }
    }
}
